// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package taskdb

import (
	"database/sql"
)

type Task struct {
	ID        int64
	Title     string
	Desc      string
	Duration  int64
	CreatedAt sql.NullTime
}
